version: '2.1'

services:

#Database container

  db:
    image: mysql:latest
    ports:
      - ${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    healthcheck:
      test: "exit 0"
    volumes:
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql 
    
#node container
  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      - APP_SERVER_PORT=${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    depends_on:
      db:
        condition:
          service_healthy
    links:
      - db
    volumes:
      - ./server:/usr/app/crash-course-server
    command: npm run start

  #react client
  client:
    build: ./client
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/usr/app/crash-course-client/src
      - ./client/public:/usr/app/crash-course-client/public
    links:
      - server
    command: npm run start
